name: request-service-prod
services:
  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
    
  client:
    image: ${ECR_REPOSITORY_URL}:${CLIENT_IMAGE_TAG}
    expose:
      - "3000:3000"
    container_name: client.request.internal
    environment:
      PRIVATE_GASI_API_URL: gasi.request.internal:8080
  gasi:
    image: ${ECR_REPOSITORY_URL}:${GASI_IMAGE_TAG}
    expose:
      - "8080:8080"
    container_name: gasi.request.internal