name: Lint code and commits

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint code and commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --save-dev -w @commitlint/cli @commitlint/config-conventional @biomejs/biome

      - name: Validate last commit with commitlint
        if: github.event_name == 'push'
        run: pnpx @commitlint/cli --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: pnpx @commitlint/cli --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Check with biome (client)
        run: pnpx biome ci .