name: Lint code and commits

on: [ push ]

jobs:
  lint:
    name: Lint code and commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --save-dev -w @commitlint/cli @commitlint/config-conventional @biomejs/biome

      - name: Validate last commit with commitlint
        run: pnpx @commitlint/cli --last --verbose

      - name: Check with biome (client)
        run: pnpx @biomejs/biome ci .